# Generated by Django 4.0.3 on 2024-10-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_superchecker_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='no', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='link',
            field=models.CharField(default='no', max_length=255),
            preserve_default=False,
        ),
    ]
