# Generated by Django 5.1.3 on 2024-12-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_superchecker_project', '0004_shoppinglist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='contents',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
